### ISSUE TITLE
File stream is dropped on writeStream()

### ISSUE THREAD

**Issue by violuke** [Superbalist/flysystem-google-cloud-storage#113]
After using the `writeStream()` function, my file handle is no longer a valid stream resource. Other providers (I've tested specifically with S3) keep the handle as a valid resource. I hope that makes sense?

```php
$someFile = tmpfile();

$filesystem->writeStream($remoteFileName, $someFile);

// This line causes a problem with this adapter, but not others
// Warning: fclose(): supplied resource is not a valid stream resource
fclose($someFile);
```

**Comment by radoslawkoziol** [comment]
@violuke You need to check if `$someFile` is a resource:

```php
if (is_resource($someFile)) {
    fclose($someFile);
}
```

**Comment by violuke** [comment]
Thanks, yes, I know I can check, but I think it's a bug that this adapter works differently to the others?

**Comment by radoslawkoziol** [comment]
@violuke it appears to be normal behavior. According to the official Flysystem documentation:

`Some SDK’s close streams after consuming them, therefore, before calling fclose on the resource, check if it’s still valid using is_resource.`

https://flysystem.thephpleague.com/v1/docs/usage/filesystem-api/

**Comment by violuke** [comment]
You're right, sorry! Thanks for sending that link, that's really helpful. I'll close this as it's not a bug then :+1:

**Comment by shopmeister** [comment]
with php 8.x we should not use that anymore, just use 

`if (!$someFile) {
    fclose($someFile);
}`
