### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by atrauzzi** [Superbalist/flysystem-google-cloud-storage#121]
Just curious, but is this project still being maintained?

**Comment by kublermdk** [comment]
I'm interested too as I was going to suggest a pull request. But given it's been 6 months since you posted this, I'm guessing not :-(

**Comment by bleuscyther** [comment]
I think there is an official package now
[thephpleague/flysystem-google-cloud-storage ](https://github.com/thephpleague/flysystem-google-cloud-storage)
