### ISSUE TITLE
Google Cloud - Connection example

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-cloud-storage#37]
Could someone provide examples on how to use the new GCloud API?

I've upgraded from v1 to v3 (this library) and I can no longer use `Google_Auth_AssertionCredentials` as the Google API library was changed to GCloud.

**Comment by matthewgoslett** [comment]
There's a very detailed usage example in the readme (root) of this repo: https://github.com/Superbalist/flysystem-google-cloud-storage/blob/master/README.md

**Comment by paulcanning** [comment]
Yea sorry, I found it not longer after posting, oops!
