### ISSUE TITLE
Possible upload issue with elFinder and v3

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-cloud-storage#38]
I'm testing out v3 of this library as I need to upload huge files, and the chnage to a streaming method should help.

However, now when I upload a large file (for now, just 100-200mb) elFinder is behaving odd, and I think it is linked to this library maybe?

Previously, the upload progress was accurate, and there would be lots of small chunked requests.

Now, there are a few small XHR requests (depending on the chunk size set in elFinder) which fills the progress bas to 100%, then there is a final request (elFinder display "Doing something") that takes X amount of time and does the full upload of the file.

This is giving me issues with timeouts if the file isn't written in enough time. I was under the impression the streaming method you implemented would solve timeout issues?

**Comment by matthewgoslett** [comment]
We unfortunately can't assist with integration with a 3rd party library.

If you can assist in debugging and help point us to where things may be going wrong in our library, we can re-open this issue.
