### ISSUE TITLE
Propagate config options to google bucket upload

### ISSUE THREAD

**Issue by beesperester** [Superbalist/flysystem-google-cloud-storage#42]
Right now you can pass an array containing upload config to writeStream, updateStream etc. after retrieving the filesystem driver via $disk->getDriver() which will essentially pass the arguments to
`protected function upload($path, $contents, Config $config)`
where the actual config of the google bucket upload happens.

I noticed, that the config arguments are prepared by another function:
```
protected function getOptionsFromConfig(Config $config)
{
	$options = [];

	if ($visibility = $config->get('visibility')) {
		$options['predefinedAcl'] = $this->getPredefinedAclForVisibility($visibility);
	} else {
		// if a file is created without an acl, it isn't accessible via the console
		// we therefore default to private
		$options['predefinedAcl'] = $this->getPredefinedAclForVisibility(AdapterInterface::VISIBILITY_PRIVATE);
	}

	return $options;
})
```

The problem I have is, that only the 'visibility' argument from $config is actually parsed, additional arguments like 'chunkSize' or 'resumable' that are essential for chunked file uploads are discarded.

I would suggest adding something along the line of this, to enable those features:
```
if ($config->has('chunkSize')) {
	$options['chunkSize'] = $config->get('chunkSize');
}

if ($config->has('resumable')) {
	$options['resumable'] = $config->get('resumable');
}
```

**Comment by matthewgoslett** [comment]
Should we just pass any other vars from the `$config` in the return array?

I don't see the need to explicitly check each one unless the function needs to sanitise or manipulate
