### ISSUE TITLE
How to configure this adapter with Elfinder?

### ISSUE THREAD

**Issue by richseyha** [Superbalist/flysystem-google-cloud-storage#45]
Dear Sir/Madam,

Please coud you help to provide me the configuration guide between Elfinder and Flysystem-google-cloud-storage?

Best Regards,

**Comment by matthewgoslett** [comment]
We unfortunately can't assist with integration with a 3rd party library.

Your best bet would be to look on their issue board and see if any other users are using a google cloud integration.
