### ISSUE TITLE
Allow metadata key in getOptionsFromConfig 

### ISSUE THREAD

**Issue by MikeyVelt** [Superbalist/flysystem-google-cloud-storage#46]
Hello there,
The getOptionsFromConfig method should accept the metadata key as a possible value.

I require this for the following properties:

"contentType": string
"contentLanguage": string
"cacheControl": string
The official google cloud documentation shows that the StorageObject allows the metadata property.
https://googlecloudplatform.github.io/google-cloud-php/#/docs/v0.20.1/storage/storageobject?method=update

And the JSON API docs shows what properties the StorageObject can contain.
https://cloud.google.com/storage/docs/json_api/v1/objects#resource

**Comment by matthewgoslett** [comment]
Thanks.
Resolved in https://github.com/Superbalist/flysystem-google-cloud-storage/pull/47
