### ISSUE TITLE
Undefined Index contentType in normalizeObject function

### ISSUE THREAD

**Issue by coastermcgee** [Superbalist/flysystem-google-cloud-storage#48]
I am running into an issue reading a directory of files from a google cloud storage bucket.
```
ErrorException in GoogleStorageAdapter.php line 193: Undefined index: contentType

/home/vagrant/Code/TestApplication/vendor/superbalist/flysystem-google-storage/src/GoogleStorageAdapter.php line 193
```

The error occurs in the normalizeObject function when I run where "testing" is my directory name:
```
$files = Storage::disk('gcs')->files('testing');
dd($files);  
```
And here is the dump of the object that causes the exception:

```
array:16 [▼
  "kind" => "storage#object"
  "id" => "testbucket/testing//1486146319340058"
  "selfLink" => "https://www.googleapis.com/storage/v1/b/testapplication/o/testing%2F"
  "name" => "testing/"
  "bucket" => "testbucket"
  "generation" => "1486146319340058"
  "metageneration" => "1"
  "timeCreated" => "2017-02-03T18:25:19.324Z"
  "updated" => "2017-02-03T18:25:19.324Z"
  "storageClass" => "STANDARD"
  "timeStorageClassUpdated" => "2017-02-03T18:25:19.324Z"
  "size" => "0"
  "md5Hash" => "1B2M2Y8AsgTpgAmY7PhCfg=="
  "mediaLink" => "https://www.googleapis.com/download/storage/v1/b/testapplication/o/testing%2F?generation=1486146319340058&alt=media"
  "crc32c" => "AAAAAA=="
  "etag" => "CJqky7vG9NECEAE="
]
```
If I mount the bucket on my local machine via the gcsfuse tool and use it as a local storage disk everything works fine and won't trigger this exception.

A possible quick fix is to check if contentType exists when setting the mimetype:
`'mimetype' => (isset($info[''contentType]) ? $info['contentType'] : ''),`

**Comment by matthewgoslett** [comment]
Just wondering, how was the object (the 'testing/' directory created?

I'm trying to see if I can replicate the issue my side.

If I create a directory via the console UI, it comes out as:
```
  [4] =>
  array(6) {
    'type' =>
    string(3) "dir"
    'dirname' =>
    string(4) "test"
    'path' =>
    string(14) "test/subfolder"
    'timestamp' =>
    int(1486200562)
    'mimetype' =>
    string(47) "application/x-www-form-urlencoded;charset=UTF-8"
    'size' =>
    string(1) "0"
  }
```

If I create one via the adapter, I get:
```
  [5] =>
  array(6) {
    'type' =>
    string(3) "dir"
    'dirname' =>
    string(4) "test"
    'path' =>
    string(15) "test/subfolder2"
    'timestamp' =>
    int(1486200772)
    'mimetype' =>
    string(24) "application/octet-stream"
    'size' =>
    string(1) "0"
  }
```

I'm just trying to see how a object can be created and have no mimetype.

**Comment by coastermcgee** [comment]
I had created the folder on my desktop, dragged my files into it then just dragged the whole folder into the mounted storage bucket in finder (mounted via gcsfuse).

**Comment by matthewgoslett** [comment]
This is patched in https://github.com/Superbalist/flysystem-google-cloud-storage/pull/51 and currently in maser.
Will push through in the next release.
