### ISSUE TITLE
Cannot move folders, file not found error

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-cloud-storage#55]
When trying to move folders, I get a File Not Found error.

I also find that my breakpoint on the copy function (line 173, GoogleStorageAdapter.php) is not being hit when moving folders, but is when moving files?

Is moving (copy/cut and pasting effectively) folders simply not supported/working?

**Comment by matthewgoslett** [comment]
This should be resolved in 5.0.2.
