### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-cloud-storage#56]
Whilst developing locally, using v5.0.0 of this library, I am getting a cURL error about the SSL certificate.

How can I disable SSL checks for this library?

Or, if I use cacert.pem, where do I need to put that to get it to work?

**Comment by matthewgoslett** [comment]
This would be an issue with the upstream package - https://github.com/GoogleCloudPlatform/google-cloud-php
