### ISSUE TITLE
Support for google/cloud 0.40 and above

### ISSUE THREAD

**Issue by zbrox** [Superbalist/flysystem-google-cloud-storage#65]
Is there anything preventing support for the newer versions of the google/cloud library?

**Comment by chrisforrence** [comment]
For what it's worth, the phpunit tests pass with google/cloud:v0.42.0

**Comment by zoidbergwill** [comment]
If it works, I'll happily accept a PR updating `composer.json`.

**Comment by zoidbergwill** [comment]
Maybe we should update the `.travis.yml` to test some of the different versions as well like [some other projects](https://github.com/django-crispy-forms/django-crispy-forms/blob/dev/.travis.yml#L11-L15) do.

I assume we can do the same thing with `composer`?

**Comment by zoidbergwill** [comment]
I've made a PR to test these changes: https://github.com/Superbalist/flysystem-google-cloud-storage/pull/67

**Comment by jason-engage** [comment]
Any way to merge the update? Can't install via composer giving minimum stability issues. Google storage already on v0.48.

I'm sure it works fine. Whats the workaround to get it installed? Thanks

**Comment by TerraSkye** [comment]
any change the PR will be merged?

**Comment by zoidbergwill** [comment]
I've merged #67
