### ISSUE TITLE
new release.

### ISSUE THREAD

**Issue by TerraSkye** [Superbalist/flysystem-google-cloud-storage#72]
As the title says its time for a new release. 
we are testing against those versions. but we cannot use them.

**Comment by zoidbergwill** [comment]
Hi @TerraSkye 

Awesome, good point. Thanks for the reminder.

I was waiting for https://github.com/Superbalist/flysystem-google-cloud-storage/pull/71 to ship, but now I'm happy to make a release.

**Comment by zoidbergwill** [comment]
I've made a [6.0.0](https://github.com/Superbalist/flysystem-google-cloud-storage/releases/tag/6.0.0) release.
