### ISSUE TITLE
suggest: using google/cloud-storage instead of google/cloud

### ISSUE THREAD

**Issue by sinkcup** [Superbalist/flysystem-google-cloud-storage#74]
now `superbalist/flysystem-google-storage` require `google/cloud:<0.50`, but my project need use `google/cloud:0.53`.

I find google had split `google/cloud` to many sub projects, such as `google/cloud-pubsub`, `google/cloud-storage`.

https://packagist.org/packages/google/cloud-storage

so, maybe it's better to require `google/cloud-storage`

**Comment by zoidbergwill** [comment]
It's a bit difficult keeping up with their velocity.

If you make a PR to allow newer versions, I'll happily merge it.

Switching to that package sounds like a good idea that we should investigate too.

**Comment by sinkcup** [comment]
I have change it, local tests is OK, but CI crashed, need change CI settings to delete "GOOGLE_CLOUD=xxx"

![image](https://user-images.githubusercontent.com/4971414/35791697-5686118a-0a84-11e8-8b0a-4bfdbc279e79.png)

![image](https://user-images.githubusercontent.com/4971414/35791679-4781b96e-0a84-11e8-9cd4-503f2cbdd645.png)

**Comment by TerraSkye** [comment]
@sinkcup  you will have to adjust the travis.yml file as well.
as it currently tests against version of google/cloud package.

**Comment by sinkcup** [comment]
OK, I have changed it

**Comment by sinkcup** [comment]
@zoidbergwill @TerraSkye someone check it?

**Comment by sinkcup** [comment]
new tag and re-create in styleci ?

**Comment by zoidbergwill** [comment]
I've created https://github.com/Superbalist/flysystem-google-cloud-storage/compare/7.0.0

**Comment by zoidbergwill** [comment]
Enabled StyleCI on this repo and the other one. 👍 

Thanks for your awesome contributions. 🙏
