### ISSUE TITLE
How to upload file (image) to Firebase ?

### ISSUE THREAD

**Issue by DVThuanDL** [Superbalist/flysystem-google-cloud-storage#79]
I have a problem: upload file (image) to Storage Firebase by PHP
Current, I don't find any function that it can resolve for this  problem.
Pls, support help me.
Thanks!

**Comment by oruiz92** [comment]
Hi! Sorry for my bad english! I solved that using bucket's url defined in project's configuration. Also use `keyFilePath` option that leads to `credentials.json` file,  generated in GCP console.

**Comment by josephlodero** [comment]
@oruiz92 Hi,

Sorry to bother you.. where can i find this credentials.json in GCP console?

**Comment by oruiz92** [comment]
Hi @josephlodero, sorry for the late response!

Check this link -> https://cloud.google.com/video-intelligence/docs/common/auth. 

I hope it helps!

**Comment by nicja** [comment]
Closed due to inactivity
