### ISSUE TITLE
google/cloud-storage version constraint

### ISSUE THREAD

**Issue by albertborsos** [Superbalist/flysystem-google-cloud-storage#83]
Is there any reason for this constraint?
https://github.com/Superbalist/flysystem-google-cloud-storage/blob/master/composer.json#L14

I am using google/cloud-storage 1.5, that is why I cannot install a package which fails on this dependency.

Thanks

**Comment by TerraSkye** [comment]
if the test pass for the higher version i don't see any reason to not bumb the version constraint.
as far is i know it was locked because we need to make sure it keeps working.
so if a PR with a constraint to 1.5 succeeds i think we can up the constraint.

**Comment by albertborsos** [comment]
Thanks. I made a PR: #84

**Comment by ftrotter** [comment]
This is a show-stopping bug for installation on current versions of php with current versions of google/cloud-storage.. 

please accept pull request if possible.

-FT
