### ISSUE TITLE
Add support for temporary URLs (Signed)

### ISSUE THREAD

**Issue by nasatome** [Superbalist/flysystem-google-cloud-storage#85]
https://cloud.google.com/storage/docs/access-control/signed-urls
Thanks for the excellent work!

**Comment by bradjones1** [comment]
https://github.com/Superbalist/flysystem-google-cloud-storage/pull/86

**Comment by callumthomson** [comment]
I also think this would be a good addition!

**Comment by nasatome** [comment]
I hope you add it, it will be very useful for many. @callumthomson

**Comment by nicja** [comment]
Fixed in 7.2.2 by #86
