### ISSUE TITLE
Change to semver for versioning

### ISSUE THREAD

**Issue by bradjones1** [Superbalist/flysystem-google-cloud-storage#87]
Thanks very much for this great package. Would you consider moving to semver-compatible versioning? I recently had to submit a change to the Drupal module using this package to pull in 7.0.0, however it doesn't appear there are any real breaking changes from 5.x, which is what it had been on. Using semantic versioning would make it easier for packages depending on this one to identify breaking changes and keep API compatibility for more minor changes. It appears every release at the moment bumps the major version.

**Comment by nicja** [comment]
Looks like we started this way and then a couple of release just went ahead and updated the major version. We will commit to semver going forward :+1:
